class Credential:
    '''
    
    Class that generates new instance of credentials

    '''

#Credentials
#account
#account_username
#account_password

#new Credentials
#choose account
#make account_username
#account_password is autogenerated
#change account_password