class Credential:

    '''
    
    Class that generates new instance of credentials

    '''
    #Credentials list
    credential_list = []

    def __init__(self,login_name, account, credential_pass):
        self.login_name = login_name
        self.account = account
        self.credential_pass = credential_pass

    def save_credential(self):
        '''
    
        method to save credentials in the ist

        '''
        Credential.credential_list.append(self)

    
#account
#account_username
#account_password

#new Credentials
#choose account
#make account_username
#account_password is autogenerated
 #change account_password